### ISSUE TITLE
access_token is ignored when access_token_secret is not passed

### ISSUE THREAD

**Issue by fletom** [maraujop/requests-oauth#14]
In some cases, such as Step 3 of https://dev.twitter.com/docs/auth/implementing-sign-twitter only the access_token is required. Right now the workaround is passing an empty string, which is ugly and non-obvious.

**Comment by maraujop** [comment]
You are right. 

Do you want me to tackle this?  Or are you also working on a patch in your fork?

Cheers,
Miguel

**Comment by fletom** [comment]
I'm working on both of these, and I'll submit a pull request soon.

**Comment by maraujop** [comment]
Version 0.4.0 has been released, it works well with requests 0.12.1 or higher. I'm closing this issue.

Cheers
