### ISSUE TITLE
Breaks with requests==0.12.1.

### ISSUE THREAD

**Issue by bryanhelmig** [maraujop/requests-oauth#25]
Looks like it expects `._enc_params` on `Request` and also the `.add_to_header()` is missing on the new CookieJar as it is a `dict`. I believe the former is fixed in dev, but the latter still exists.

Can provide more details, but basically, upgrading to 0.12.1 should result in the same Exceptions.

**Comment by maraujop** [comment]
Version 0.4.0 has just been released, it works well with requests 0.12.1 or higher. Let me know if it works for you.

thanks, cheers
Miguel

**Comment by immunda** [comment]
So awesome! Glad you got a ton of fixes sorted for this @maraujop; loving your work.

**Comment by maraujop** [comment]
Thanks Phil, I'm glad you like it :D

**Comment by bryanhelmig** [comment]
Wonderful! Thanks @maraujop!
