### ISSUE TITLE
AttributeError in urllib.py raised using requests-oauth and Imgur's API

### ISSUE THREAD

**Issue by ollieglass** [maraujop/requests-oauth#26]
I'm calling the [Imgur API](http://api.imgur.com/resources_auth) and seeing "AttributeError: 'list' object has no attribute 'rstrip'" raised by urllib.py

I've documented it here https://gist.github.com/2732412 

Any ideas?

**Comment by maraujop** [comment]
Hi Ollie,

Most likely you are doing 3-legged Auth wrong. I've improved the README section for this topic:
https://github.com/maraujop/requests-oauth#3-legged-authorization

I've added some tests for Imgur API and all of them are passing. So make sure you are using latest requests-oauth 0.4.0 and that you are getting user's access token correctly.

Let me know if I can close the issue.

Thanks, cheers
Miguel

**Comment by ollieglass** [comment]
Hi Miguel,

thanks for looking into this. I suspect you're right, but I'm getting an error with your code on this line:

response = requests.post('http://api.imgur.com/oauth/access_token', {'oauth_verifier': oauth_verifier}, hooks=new_imgur_oauth_hook)

Traceback (most recent call last):
  File "./imgur.py", line 116, in <module>
    response = requests.post('http://api.imgur.com/oauth/access_token', {'oauth_verifier': oauth_verifier}, hooks=new_imgur_oauth_hook)
  File "/Users/ollieglass/.virtualenvs/imgur_tests/lib/python2.7/site-packages/requests/api.py", line 85, in post
    return request('post', url, data=data, *_kwargs)
  File "/Users/ollieglass/.virtualenvs/imgur_tests/lib/python2.7/site-packages/requests/api.py", line 40, in request
    return s.request(method=method, url=url, *_kwargs)
  File "/Users/ollieglass/.virtualenvs/imgur_tests/lib/python2.7/site-packages/requests/sessions.py", line 213, in request
    args[attr] = merge_kwargs(local_val, session_val)
  File "/Users/ollieglass/.virtualenvs/imgur_tests/lib/python2.7/site-packages/requests/sessions.py", line 41, in merge_kwargs
    kwargs.update(local_kwarg)
TypeError: 'OAuthHook' object is not iterable

Any ideas?

**Comment by maraujop** [comment]
No problem Ollie,

I just realized I had a typo in that line. The correct line is:

``` python
response = requests.post('http://api.imgur.com/oauth/access_token', {'oauth_verifier': oauth_verifier}, hooks={'pre_request': new_imgur_oauth_hook})
```

I've just pushed a fix for the docs, sorry about that. 

One more thing, most likely you want to use `params` for get, not `data`:

``` python
r = client.get("http://api.imgur.com/2/stats.json", params={"view":"all"})
```

Cheers,
Miguel
