### ISSUE TITLE
to_utf8_if_string not defined

### ISSUE THREAD

**Issue by jqxl0205** [maraujop/requests-oauth#7]
see here https://github.com/maraujop/requests-oauth/blob/dev/oauth_hook/auth.py#L28

**Comment by maraujop** [comment]
Completely right. Sorry for taking so long to handle the issue, I've been extremely busy last 3 weeks.

Thanks for submitting the issue and patch. I've added you to AUTHORS. Let me know your name if you want me to add it too.
