### ISSUE TITLE
x.encode('utf-8') may raise UnicodeDecodeError

### ISSUE THREAD

**Issue by jqxl0205** [maraujop/requests-oauth#8]
see here https://github.com/maraujop/requests-oauth/blob/dev/oauth_hook/auth.py#L23

x.encode('utf-8') may raise UnicodeDecodeError for in request  self.data 's value is encoded to utf-8

so, here should do like this

``` python
x.encode('utf-8') if isinstance(x, unicode) else x
```

**Comment by maraujop** [comment]
Thanks again, fixed :)
